### ISSUE TITLE
Scrollbars in the menu when on windows

### ISSUE THREAD

**Issue by FrankMerema** [FrontMen/frontmen.nl#7]
When on windows opening the side menu, scrollbars are shown. This is default on windows, but at least the overflow-x should be disabled ;)

![scrollbars frontmen nl](https://user-images.githubusercontent.com/5937851/45468890-5b68c300-b727-11e8-9d55-caac60fcd2f0.png)

**Comment by msegers** [comment]
FYI: this also occurs if you have a "windows mouse" connected to your macbook.

**Comment by FrankMerema** [comment]
Its also default behavior on windows ;)
