### ISSUE TITLE
Hover of submenu items is slightly off

### ISSUE THREAD

**Issue by msegers** [FrontMen/frontmen.nl#9]
The hover (and click) behavior of submenu items in the navbar seems incorrect, when you hover directly below the text of the (sub) menu item it already catches the mouse on the next element. 
For regular/first level  menu items, this seems to be fine.

For reference:
![submenuitems2](https://user-images.githubusercontent.com/3832687/45469601-738e1180-b72a-11e8-82f7-1a166e3d41cd.png)

**Comment by lassecapel** [comment]
30px margin on links overlap because of list item-height. Could be fixed by combining padding and margins instead of using paddings only
